version: "3.1"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      - POSTGRES_DB=polznak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  web:
    build: core
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
