# Generated by Django 3.2.8 on 2021-11-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polznak_entities', '0004_alter_grades_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSpecialWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unque_and_long_words', models.JSONField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polznak_entities.profile')),
            ],
        ),
    ]
