# Generated by Django 3.2.8 on 2021-10-22 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'interest area',
                'verbose_name_plural': 'interest areas',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=5, verbose_name='language_code')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('send_at', models.DateTimeField(auto_now=True, verbose_name='Send at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polznak_entities.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('details', models.TextField(blank=True, verbose_name='Additional information')),
                ('interests', models.ManyToManyField(to='polznak_entities.InterestArea')),
                ('knows_languages', models.ManyToManyField(to='polznak_entities.Language', verbose_name='Knows languages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polznak_entities.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSeenByProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now=True, verbose_name='Seen at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polznak_entities.message')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polznak_entities.profile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_by', through='polznak_entities.MessageSeenByProfile', to='polznak_entities.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='polznak_entities.profile'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polznak_entities.post'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(to='polznak_entities.Profile'),
        ),
    ]
