# Generated by Django 3.2.8 on 2021-10-24 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polznak_entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('send_at', models.DateTimeField(auto_now=True, verbose_name='Send at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polznak_entities.post')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_sender', to='polznak_entities.profile')),
            ],
        ),
    ]
