# Generated by Django 3.2.8 on 2021-10-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polznak_entities', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.IntegerField(choices=[(-1, 'Dislike'), (1, 'Like')], default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polznak_entities.post')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_sender', to='polznak_entities.profile')),
            ],
        ),
    ]
