# Generated by Django 3.2.8 on 2021-10-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polznak_entities', '0003_useropinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polznak_entities.conversation')),
                ('user_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_given', to='polznak_entities.profile')),
                ('user_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_received', to='polznak_entities.profile')),
            ],
        ),
    ]
