# Generated by Django 3.2.8 on 2021-11-14 06:42

from django.db import migrations, models
import polznak_entities.validators


class Migration(migrations.Migration):

    dependencies = [
        ('polznak_entities', '0003_alter_useropinion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(validators=[polznak_entities.validators.grade_validator]),
        ),
    ]
