POST http://localhost:8000/api/posts/
Content-Type: application/json
Authorization: token c94b17ecbfc8968346375cca5b2066ce6e045c95

{
  "title": "Заголовок поста",
  "content": "Содержание поста"
}

###

GET http://localhost:8000/api/posts/?skip=0&count=10
Accept: application/json
Authorization: token 077e829e5c617e0385fe471f130e5f43f95ad0aa

###

POST http://localhost:8000/api/likes/
Content-Type: application/json
Authorization: token 077e829e5c617e0385fe471f130e5f43f95ad0aa

{
  "post_id": 1,
  "grade": 1
}

###

GET http://localhost:8000/api/likes/?post_id=1
Accept: application/json
Authorization: token 077e829e5c617e0385fe471f130e5f43f95ad0aa
